basePath: /
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a Fiber application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Swagger Example API
  version: "1.0"
paths:
  /hello:
    get:
      description: get string hello
      operationId: hello
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Show a hello message
swagger: "2.0"
